### ISSUE TITLE
ala-hub: Error loading SimpleDwCCSVheaderUTF8.txt

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/downloads-plugin#37]
_From @javier-molina on December 5, 2017 1:3_

The following is poping in biocache-test.ala.org when downloading records on ala-hub/downloads-plugin

```
java.io.FileNotFoundException: class path resource [SimpleDwCCSVheaderUTF8.txt] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/var/lib/tomc
at7/webapps-biocache-test.ala.org.au/ROOT/WEB-INF/lib/downloads-plugin-1.6-SNAPSHOT.jar!/SimpleDwCCSVheaderUTF8.txt
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:215)
        at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:53)
        at org.springframework.core.io.Resource$getFile$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at au.org.ala.downloads.BiocacheService.getDwCFieldsOrdered(BiocacheService.groovy:167)
        at au.org.ala.downloads.BiocacheService$$FastClassBySpringCGLIB$$a7b6079c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at au.org.ala.downloads.BiocacheService$$EnhancerBySpringCGLIB$$e625a46b.getDwCFieldsOrdered(<generated>)
        at au.org.ala.downloads.BiocacheService$getDwCFieldsOrdered$3.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at au.org.ala.downloads.BiocacheService.orderFieldsByDwC(BiocacheService.groovy:125)
        at au.org.ala.downloads.BiocacheService$orderFieldsByDwC$2.callCurrent(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at au.org.ala.downloads.BiocacheService.getDwCFields(BiocacheService.groovy:114)
        at au.org.ala.downloads.BiocacheService$$FastClassBySpringCGLIB$$a7b6079c.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
        at au.org.ala.downloads.BiocacheService$$EnhancerBySpringCGLIB$$e625a46b.getDwCFields(<generated>)
        at au.org.ala.downloads.BiocacheService$getDwCFields.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at au.org.ala.downloads.DownloadService.triggerDownload(DownloadService.groovy:44)
        at au.org.ala.downloads.DownloadService$$FastClassBySpringCGLIB$$d2deaace.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669)

```

_Copied from original issue: AtlasOfLivingAustralia/maintenance#225_

**Comment by adam-collins** [comment]
Presumably fixed because no error anymore.
